### ISSUE TITLE
Make landingpage configurable at run time

### ISSUE THREAD

**Issue by minottic** [SciCatProject/LandingPageServer#327]
**Is your feature request related to a problem? Please describe.**
Currently, the configuration is hadrcoded in the docker image because is supplied to angular before the build. The docker image should be configurable at run time

**Describe the solution you'd like**
We can adopt a solution similar to [this](https://imran3.medium.com/runtime-configuration-for-angular-c9d9082e1de3)

See example: 
[here](https://github.com/SciCatProject/frontend/blob/master/src/app/app-config.service.ts) 
[and here ](https://github.com/SciCatProject/frontend/blob/master/src/app/datasets/dataset-table/dataset-table.component.ts#L60)

**Comment by rkweehinzmann** [comment]
Thanks for the pointers! I crreated a new branch ```rt_config``` where I'll put my modifications. 

It seems i need to change 
- app.module.ts: add APP_INITIALIZER 
- app-config.service.ts: to call and save (?) the new configuration in spe
- add a json in assets/

to begin with. For now it's unclear what the appInsightKey does.

**Comment by rkweehinzmann** [comment]
79f76d39d019ce1e6df00cf1d0a9b83c17a223e2 produces in frontend no errors, lacks still functionality.

**Comment by minottic** [comment]
@rkweehinzmann I have noticed the config can be loaded already at run time [here](https://github.com/SciCatProject/LandingPageServer/blob/develop/src/app/app-config.service.ts). So maybe your change is not needed, I am afraid I referred to an older version then. Could you then please try to use the landing page as is, just by supplying the config at run time (by having a file in `/usr/share/nginx/html/assets/config.json`) and see if that is rendered correctly in the browser?
